pm_tool:
  type: github-projects
  configured_at: '2026-01-31T13:34:28.603Z'
  config: {}
sync_behavior:
  auto_sync_on_status_change: true
  create_tasks_on_story_creation: false
  bidirectional_sync: false
